using Test

@testset "CosmoRec.jl" begin
    # Resource order (no scientific coupling: this file needs only `Test` and COSMOREC_NATIVE_DATA_DIR; its large Mooncake workers run in fresh sequential
    # processes with their own helpers and fixed seeds): run the ~10-13 GB workers while this parent process is still light, instead of after it has
    # retained MC/JIT state from the in-process tests below (the monolithic run was OOM-killed at parent 12-16 GiB + worker 10-13 GiB).
    include("chunk11b_quadplan_stage_ad.jl")
    include("chunk1a_stiff_ad_probe.jl")
    include("chunk1b_radiation_shaped_probe.jl")
    include("chunk1c_nonlinear_probe.jl")
    include("chunk1d_native_fixture.jl")
    include("chunk2_rate_table_native.jl")
    include("chunk2_rate_table_ad.jl")
    include("chunk3a_rhs_native.jl")
    include("chunk3a_rhs_ad.jl")
    include("chunk3b_rhs_native.jl")
    include("chunk3b_rhs_ad.jl")
    include("chunk3c_hiabs_native.jl")
    include("chunk3c_hiabs_ad.jl")
    include("chunk3d_fcn_native.jl")
    include("chunk3d_fcn_ad.jl")
    include("chunk3e_dpesc_native.jl")
    include("chunk3e_dpesc_ad.jl")
    include("chunk4a_saha_native.jl")
    include("chunk4a_saha_ad.jl")
    include("chunk4b_cosmos_native.jl")
    include("chunk4b_cosmos_ad.jl")
    include("chunk4c_recfast_native.jl")
    include("chunk4c_recfast_ad.jl")
    include("chunk4d_helium_switch_native.jl")
    include("chunk4d_helium_switch_ad.jl")
    include("chunk5a_ode_rhs_native.jl")
    include("chunk5a_ode_rhs_ad.jl")
    include("chunk5b_ode_pass_native.jl")
    include("chunk5c_recfast_tail_native.jl")
    include("chunk5d_output_native.jl")
    include("chunk5e_history_ad.jl")
    include("chunk5f_prepared_jac_mooncake.jl")
    include("chunk5g_rhs_workspace.jl")
    include("chunk5h_jacobian_workspace.jl")
    include("chunk5i_time_gradient_workspace.jl")
    include("chunk6a_pde_coefficients_native.jl")
    include("chunk6a_pde_coefficients_ad.jl")
    include("chunk6b_pd_only_coefficients.jl")
    include("chunk7a_pde_setup_native.jl")
    include("chunk7b_pde_define_native.jl")
    include("chunk7c_pde_march_native.jl")
    include("chunk8a_pde_integrals_native.jl")
    include("chunk9a_diffusion_feedback_native.jl")
    include("chunk7_10_pde_ad.jl")
    include("chunk10a_runmode0_native.jl")
    include("chunk10b_runmode0_ad.jl")
    include("chunk10d_background_link_ad.jl")
    include("chunk11_quadplan_ad.jl")
    include("chunk11c_quadplan_cached_fit.jl")
end
